server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/2fa-demo}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

app:
  security:
    action-token-ttl-seconds: 300
    required-acr: gold
    required-amr: otp

logging:
  level:
    com.example.twofa: DEBUG
    org.springframework.security: INFO
